-- ==============================================================================
-- SOR CONNECT - SUPABASE / POSTGRESQL DATABASE SCHEMA & SEED SCRIPT
-- ==============================================================================
-- This script creates all tables, constraints, indexes, RLS security policies, 
-- and initial seed data for the Sor Connect platform.
-- ==============================================================================

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. PROJECTS TABLE
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client TEXT NOT NULL,
    location TEXT NOT NULL,
    capacity TEXT NOT NULL,
    sector_or_type TEXT NOT NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. SUBMISSIONS TABLE (Form Inquiries, Quotes, & Leads)
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    whatsapp TEXT,
    monthly_bill TEXT,
    pincode TEXT,
    note TEXT,
    status TEXT DEFAULT 'New' NOT NULL,
    subject TEXT DEFAULT 'Solar Inquiry',
    source_url TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. ABOUT GALLERY CAROUSEL TABLE
CREATE TABLE IF NOT EXISTS public.about_gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    badge TEXT DEFAULT 'Field Showcase',
    description TEXT,
    location TEXT,
    image TEXT NOT NULL,
    display_order INT DEFAULT 1 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==============================================================================
-- INDEXES FOR OPTIMAL QUERY PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_projects_category_id ON public.projects(category_id);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON public.submissions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON public.submissions(status);
CREATE INDEX IF NOT EXISTS idx_about_gallery_order ON public.about_gallery(display_order ASC);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) & ACCESS POLICIES
-- ==============================================================================
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_gallery ENABLE ROW LEVEL SECURITY;

-- Categories: Allow public read and full admin access
CREATE POLICY "Public can view categories" ON public.categories 
    FOR SELECT USING (true);
CREATE POLICY "Full access to categories" ON public.categories 
    FOR ALL USING (true) WITH CHECK (true);

-- Projects: Allow public read and full admin access
CREATE POLICY "Public can view projects" ON public.projects 
    FOR SELECT USING (true);
CREATE POLICY "Full access to projects" ON public.projects 
    FOR ALL USING (true) WITH CHECK (true);

-- Submissions: Allow public form submission and admin read/update
CREATE POLICY "Public can insert submissions" ON public.submissions 
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Full access to submissions" ON public.submissions 
    FOR ALL USING (true) WITH CHECK (true);

-- About Gallery: Allow public read and full admin access
CREATE POLICY "Public can view gallery" ON public.about_gallery 
    FOR SELECT USING (true);
CREATE POLICY "Full access to gallery" ON public.about_gallery 
    FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- INITIAL SEED DATA
-- ==============================================================================

-- Seed Categories
INSERT INTO public.categories (id, name, slug, description)
VALUES 
    (1, 'EPC Projects', 'epc', 'Engineering, Procurement & Construction turnkey industrial and commercial solar installations.'),
    (2, 'I&C / O&M Projects', 'ic_om', 'Installation, Testing, Commissioning and 25-Year Operation & Maintenance accounts.')
ON CONFLICT (slug) DO UPDATE 
SET name = EXCLUDED.name, description = EXCLUDED.description;

-- Reset Category Identity Sequence
SELECT setval(pg_get_serial_sequence('public.categories', 'id'), COALESCE(MAX(id), 1)) FROM public.categories;

-- Seed Projects
INSERT INTO public.projects (client, location, capacity, sector_or_type, category_id)
VALUES 
    -- EPC Projects (Category ID = 1)
    ('Vishwaraj Environment Ltd', 'Agra', '2315 KW', 'STP', 1),
    ('Rana Bai Marble & Granite', 'Kishangarh, Ajmer', '324 KW', 'Marble', 1),
    ('KGK Dia Processing', 'Jasdan, Rajkot', '250 KW', 'Diamond', 1),
    ('Arihant Oil & Mills Ltd', 'Sri Ganganagar', '240 KW', 'Oil', 1),
    ('Quality Marble Export', 'Jalore', '200 KW', 'Marble', 1),
    
    -- I&C / O&M Projects (Category ID = 2)
    ('Shreej Solar Solution', 'Surat', '1300 KW', 'I&C', 2),
    ('Yutaka Autoparts Pvt Ltd', 'Bhiwadi', '736 KW', 'O&M', 2),
    ('Wonder Cement Terminal', 'Nimbahera', '1100 KW', 'I&C', 2),
    ('Jaipur Rugs Manufacturing', 'Jaipur', '450 KW', 'O&M', 2);

-- Seed About Gallery Slides
INSERT INTO public.about_gallery (title, subtitle, badge, description, location, image, display_order)
VALUES 
    (
        'Sor Connect Engineering & Operations Team',
        '130+ dedicated solar specialists driving excellence across 13 Indian states',
        'Our People & Leadership',
        '130+ dedicated solar specialists driving excellence across 13 Indian states',
        'HQ Jaipur & Pan-India Sites',
        'assets/our-team.jpg',
        1
    ),
    (
        'Industrial Rooftop Solar EPC Plant',
        '2,315 kW Turnkey Industrial Installation in Kishangarh, Rajasthan',
        'Turnkey EPC',
        '2,315 kW Turnkey Industrial Installation in Kishangarh, Rajasthan',
        'Kishangarh, Rajasthan',
        'assets/svc-epc-1.jpg',
        2
    ),
    (
        '3D Plant Modeling & Structural Engineering',
        'Helioscope & PVsyst Optimized Layouts with 25-Year Simulation',
        'Engineering & Design',
        'Helioscope & PVsyst Optimized Layouts with 25-Year Generation Simulation',
        'Engineering HQ, Jaipur',
        'assets/svc-design-1.jpg',
        3
    ),
    (
        'On-Ground Grid Synchronisation & Commissioning',
        'State DISCOM Compliant HT Connectivity & Statutory Clearances',
        'I&C Execution',
        'State DISCOM Compliant HT Connectivity & Statutory Safety Clearances',
        'Bhiwadi Industrial Zone',
        'assets/svc-inst-1.jpg',
        4
    ),
    (
        'Predictive O&M & Robotic Module Cleaning',
        '150+ MW Solar Assets Under Active 24/7 SCADA Health Monitoring',
        'Operation & Maintenance',
        '150+ MW Solar Assets Under Active 24/7 SCADA Health Monitoring',
        'Agra Regional Hub',
        'assets/svc-om-1.jpg',
        5
    ),
    (
        'PM-KUSUM Feeder Solarisation',
        'Empowering Agricultural Green Energy & 25-Year Guaranteed PPA Revenue',
        'PM-KUSUM Agri-Solar',
        'Empowering Agricultural Green Energy & 25-Year Guaranteed PPA Revenue',
        'Western Rajasthan',
        'assets/svc-kusum-1.jpg',
        6
    );
