-- ==============================================================================
-- SOR CONNECT - SUPABASE / POSTGRESQL DATABASE SCHEMA & MIGRATION SCRIPT
-- ==============================================================================
-- This script is 100% idempotent: it safely creates or updates tables, adds
-- missing columns (e.g. description), drops/re-creates policies cleanly,
-- and inserts initial data without throwing errors on existing databases.
-- ==============================================================================

-- 1. CREATE TABLES (IF NOT EXIST)
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client TEXT NOT NULL,
    location TEXT NOT NULL,
    capacity TEXT NOT NULL,
    sector_or_type TEXT,
    category_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    whatsapp TEXT,
    monthly_bill TEXT,
    pincode TEXT,
    note TEXT,
    status TEXT DEFAULT 'New',
    subject TEXT DEFAULT 'Solar Inquiry',
    source_url TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.about_gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    badge TEXT DEFAULT 'Field Showcase',
    description TEXT,
    location TEXT,
    image TEXT NOT NULL,
    display_order INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==============================================================================
-- 2. ENSURE ALL COLUMNS EXIST (SAFE FOR PRE-EXISTING TABLES)
-- ==============================================================================
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());

ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS client TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS capacity TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS sector_or_type TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());

ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS monthly_bill TEXT;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS pincode TEXT;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'New';
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS subject TEXT DEFAULT 'Solar Inquiry';
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());

ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS subtitle TEXT;
ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS badge TEXT DEFAULT 'Field Showcase';
ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS display_order INT DEFAULT 1;
ALTER TABLE public.about_gallery ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());

-- Ensure unique constraint on categories.slug
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'categories_slug_key'
    ) THEN
        ALTER TABLE public.categories ADD CONSTRAINT categories_slug_key UNIQUE (slug);
    END IF;
EXCEPTION
    WHEN OTHERS THEN NULL;
END $$;

-- ==============================================================================
-- 3. INDEXES FOR PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_projects_category_id ON public.projects(category_id);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON public.submissions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON public.submissions(status);
CREATE INDEX IF NOT EXISTS idx_about_gallery_order ON public.about_gallery(display_order ASC);

-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS) & CLEAN POLICY CREATION
-- ==============================================================================
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_gallery ENABLE ROW LEVEL SECURITY;

-- Drop old policies to avoid duplicate errors
DROP POLICY IF EXISTS "Public can view categories" ON public.categories;
DROP POLICY IF EXISTS "Full access to categories" ON public.categories;
DROP POLICY IF EXISTS "Public can view projects" ON public.projects;
DROP POLICY IF EXISTS "Full access to projects" ON public.projects;
DROP POLICY IF EXISTS "Public can insert submissions" ON public.submissions;
DROP POLICY IF EXISTS "Full access to submissions" ON public.submissions;
DROP POLICY IF EXISTS "Public can view gallery" ON public.about_gallery;
DROP POLICY IF EXISTS "Full access to gallery" ON public.about_gallery;

-- Re-create clean permissive policies
CREATE POLICY "Public can view categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Full access to categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public can view projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Full access to projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public can insert submissions" ON public.submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Full access to submissions" ON public.submissions FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public can view gallery" ON public.about_gallery FOR SELECT USING (true);
CREATE POLICY "Full access to gallery" ON public.about_gallery FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- 5. INITIAL SEED DATA
-- ==============================================================================

-- Seed / Upsert Categories
INSERT INTO public.categories (id, name, slug, description)
VALUES 
    (1, 'EPC Projects', 'epc', 'Engineering, Procurement & Construction turnkey industrial and commercial solar installations.'),
    (2, 'I&C / O&M Projects', 'ic_om', 'Installation, Testing, Commissioning and 25-Year Operation & Maintenance accounts.')
ON CONFLICT (slug) DO UPDATE 
SET name = EXCLUDED.name, description = EXCLUDED.description;

-- Ensure sequence matches highest ID
SELECT setval(pg_get_serial_sequence('public.categories', 'id'), COALESCE((SELECT MAX(id) FROM public.categories), 1));

-- Seed Projects (only if table is empty)
INSERT INTO public.projects (client, location, capacity, sector_or_type, category_id)
SELECT p.client, p.location, p.capacity, p.sector_or_type, p.category_id
FROM (
    VALUES 
        ('Vishwaraj Environment Ltd', 'Agra', '2315 KW', 'STP', 1),
        ('Rana Bai Marble & Granite', 'Kishangarh, Ajmer', '324 KW', 'Marble', 1),
        ('KGK Dia Processing', 'Jasdan, Rajkot', '250 KW', 'Diamond', 1),
        ('Arihant Oil & Mills Ltd', 'Sri Ganganagar', '240 KW', 'Oil', 1),
        ('Quality Marble Export', 'Jalore', '200 KW', 'Marble', 1),
        ('Shreej Solar Solution', 'Surat', '1300 KW', 'I&C', 2),
        ('Yutaka Autoparts Pvt Ltd', 'Bhiwadi', '736 KW', 'O&M', 2),
        ('Wonder Cement Terminal', 'Nimbahera', '1100 KW', 'I&C', 2),
        ('Jaipur Rugs Manufacturing', 'Jaipur', '450 KW', 'O&M', 2)
) AS p(client, location, capacity, sector_or_type, category_id)
WHERE NOT EXISTS (SELECT 1 FROM public.projects LIMIT 1);

-- Seed Gallery Slides (only if table is empty)
INSERT INTO public.about_gallery (title, subtitle, badge, description, location, image, display_order)
SELECT g.title, g.subtitle, g.badge, g.description, g.location, g.image, g.display_order
FROM (
    VALUES
        (
            'Sor Connect Engineering & Operations Team',
            '130+ dedicated solar specialists driving excellence across 13 Indian states',
            'Our People & Leadership',
            '130+ dedicated solar specialists driving excellence across 13 Indian states',
            'HQ Jaipur & Pan-India Sites',
            'assets/our-team.jpg',
            1
        ),
        (
            'Industrial Rooftop Solar EPC Plant',
            '2,315 kW Turnkey Industrial Installation in Kishangarh, Rajasthan',
            'Turnkey EPC',
            '2,315 kW Turnkey Industrial Installation in Kishangarh, Rajasthan',
            'Kishangarh, Rajasthan',
            'assets/svc-epc-1.jpg',
            2
        ),
        (
            '3D Plant Modeling & Structural Engineering',
            'Helioscope & PVsyst Optimized Layouts with 25-Year Simulation',
            'Engineering & Design',
            'Helioscope & PVsyst Optimized Layouts with 25-Year Generation Simulation',
            'Engineering HQ, Jaipur',
            'assets/svc-design-1.jpg',
            3
        ),
        (
            'On-Ground Grid Synchronisation & Commissioning',
            'State DISCOM Compliant HT Connectivity & Statutory Clearances',
            'I&C Execution',
            'State DISCOM Compliant HT Connectivity & Statutory Safety Clearances',
            'Bhiwadi Industrial Zone',
            'assets/svc-inst-1.jpg',
            4
        ),
        (
            'Predictive O&M & Robotic Module Cleaning',
            '150+ MW Solar Assets Under Active 24/7 SCADA Health Monitoring',
            'Operation & Maintenance',
            '150+ MW Solar Assets Under Active 24/7 SCADA Health Monitoring',
            'Agra Regional Hub',
            'assets/svc-om-1.jpg',
            5
        ),
        (
            'PM-KUSUM Feeder Solarisation',
            'Empowering Agricultural Green Energy & 25-Year Guaranteed PPA Revenue',
            'PM-KUSUM Agri-Solar',
            'Empowering Agricultural Green Energy & 25-Year Guaranteed PPA Revenue',
            'Western Rajasthan',
            'assets/svc-kusum-1.jpg',
            6
        )
) AS g(title, subtitle, badge, description, location, image, display_order)
WHERE NOT EXISTS (SELECT 1 FROM public.about_gallery LIMIT 1);
